name: Build FK Muzik EXE
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g nativefier
      - run: md FK-Muzik-exe-build
      - run: copy index.html FK-Muzik-exe-build\
      - run: copy style.css FK-Muzik-exe-build\
      - run: copy app.js FK-Muzik-exe-build\
      - run: nativefier --name "FKMuzik" FK-Muzik-exe-build\
      - uses: actions/upload-artifact@v4
        with:
          name: FK_Muzik_Windows
          path: FKMuzik-win32-x64\
